### ISSUE TITLE
Add support for all autoimported Elm standard functions

### ISSUE THREAD

**Issue by wende** [wende/elmchemy#8]
From https://github.com/elm-lang/core#default-imports :

- [x] import Basics exposing (..) #25 
- [x] import List exposing ( List, (::) ) #60 
- [x] import Maybe exposing ( Maybe( Just, Nothing ) ) #61 
- [x] import Result exposing ( Result( Ok, Err ) ) #62 
- [x] import String #63 
- [x] import Tuple #64 
- [x] import Debug #65 
- [ ] ~import Platform exposing ( Program )~
- [ ] ~import Platform.Cmd exposing ( Cmd, (!) )~
- [ ] ~import Platform.Sub exposing ( Sub )~

## Example:
```elm
a >> b >> c
```
->
```elixir
fn arg -> arg |> a |> b |> c end  
```
